### ISSUE TITLE
Removal of favourites doesn't reload the page with updated favourites

### ISSUE THREAD

**Issue by anthonynikhilreddy** [gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2#129] opened 2024-04-12 05:33 UTC
Removal of favourites doesn't reload the page with updated favourites and on manual reload the message appearing is not related to favourites page.

![image](https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/assets/54550550/deffc7e4-b015-4c2c-a003-6edcea047805)

![image](https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/assets/54550550/81d0612c-bd9f-4288-aa6f-f2195a8e3207)

![image](https://github.com/gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2/assets/54550550/62b581f7-0190-4159-a38e-61b7226fe27c)

**Comment by aru456** [comment] 2024-04-17 03:29
It's a feature, not a bug if a user accidentally removes the favorite he can still re-favorite the listing. The "right error" message is now merged into Master branch

**Closed as completed by aru456** 2024-04-17 03:30 UTC
